package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.43

import (
	"adtec/backend/src/graphql/model"
	"adtec/backend/src/router/accountBankingRouter"
	"context"
)

// CreateAccountBanking is the resolver for the createAccountBanking field.
func (r *mutationResolver) CreateAccountBanking(ctx context.Context, input model.CreateAccountBankingInput) (*model.AccountBanking, error) {
	return accountBankingRouter.Create(ctx, input)
}

// DeleteAccountBanking is the resolver for the deleteAccountBanking field.
func (r *mutationResolver) DeleteAccountBanking(ctx context.Context, id string) (*model.DeletionResult, error) {
	return accountBankingRouter.Delete(ctx, id)
}

// AccountBankingByID is the resolver for the accountBankingById field.
func (r *queryResolver) AccountBankingByID(ctx context.Context, id string) (*model.AccountBanking, error) {
	return accountBankingRouter.Get(ctx, id)
}

// GetAllAccountBankings is the resolver for the getAllAccountBankings field.
func (r *queryResolver) GetAllAccountBankings(ctx context.Context, accountBankingsFilter model.AccountBankingsFilter) ([]*model.AccountBanking, error) {
	return accountBankingRouter.GetAll(ctx, accountBankingsFilter)
}
