package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.43

import (
	"adtec/backend/src/graphql/model"
	"adtec/backend/src/router/adPaymentRouter"
	"context"
)

// CreateAdPayment is the resolver for the createAdPayment field.
func (r *mutationResolver) CreateAdPayment(ctx context.Context, input model.CreateAdPaymentInput) (*model.AdPayments, error) {
	return adPaymentRouter.Create(ctx, input)
}

// UpdateAdPayment is the resolver for the updateAdPayment field.
func (r *mutationResolver) UpdateAdPayment(ctx context.Context, input model.UpdateAdPaymentInput) (*model.AdPayments, error) {
	return adPaymentRouter.Update(ctx, input)
}

// AdPaymentByID is the resolver for the adPaymentById field.
func (r *queryResolver) AdPaymentByID(ctx context.Context, advertisementID string) (*model.AdPayments, error) {
	return adPaymentRouter.Get(ctx, advertisementID)
}

// GetAllAdPayments is the resolver for the getAllAdPayments field.
func (r *queryResolver) GetAllAdPayments(ctx context.Context, adPaymentFilter *model.AdPaymentFilter) ([]*model.AdPayments, error) {
	return adPaymentRouter.GetAll(ctx, adPaymentFilter)
}
