package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.43

import (
	"adtec/backend/src/graphql/model"
	"adtec/backend/src/router/advertisementCpmRouter"
	"context"
)

// CreateAdvertisementCpm is the resolver for the createAdvertisementCPM field.
func (r *mutationResolver) CreateAdvertisementCpm(ctx context.Context, input model.CreateAdvertisementCPMInput) (*model.AdvertisementCPMs, error) {
	return advertisementCpmRouter.Create(ctx, input)
}

// UpdateAdvertisementCpm is the resolver for the updateAdvertisementCPM field.
func (r *mutationResolver) UpdateAdvertisementCpm(ctx context.Context, input model.UpdateAdvertisementCPMInput) (*model.AdvertisementCPMs, error) {
	return advertisementCpmRouter.Update(ctx, input)
}

// AdvertisementCPMByID is the resolver for the advertisementCPMById field.
func (r *queryResolver) AdvertisementCPMByID(ctx context.Context, id string) (*model.AdvertisementCPMs, error) {
	return advertisementCpmRouter.Get(ctx, id)
}
