package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.43

import (
	"adtec/backend/src/graphql/model"
	"adtec/backend/src/router/budgetRouter"
	"context"
)

// CreateBudget is the resolver for the createBudget field.
func (r *mutationResolver) CreateBudget(ctx context.Context, input model.CreateBudgetInput) (*model.Budgets, error) {
	return budgetRouter.Create(ctx, input)
}

// UpdateBudget is the resolver for the updateBudget field.
func (r *mutationResolver) UpdateBudget(ctx context.Context, input model.UpdateBudgetInput) (*model.Budgets, error) {
	return budgetRouter.Update(ctx, input)
}

// BudgetByID is the resolver for the budgetById field.
func (r *queryResolver) BudgetByID(ctx context.Context, id string) (*model.Budgets, error) {
	return budgetRouter.Get(ctx, id)
}
