package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.43

import (
	"adtec/backend/src/graphql/model"
	"adtec/backend/src/router/campaignRouter"
	"context"
)

// CreateCampaign is the resolver for the createCampaign field.
func (r *mutationResolver) CreateCampaign(ctx context.Context, input model.CreateCampaignInput) (*model.Campaigns, error) {
	return campaignRouter.Create(ctx, input)
}

// UpdateCampaign is the resolver for the updateCampaign field.
func (r *mutationResolver) UpdateCampaign(ctx context.Context, input model.UpdateCampaignInput) (*model.Campaigns, error) {
	return campaignRouter.Update(ctx, input)
}

// DeleteCampaign is the resolver for the deleteCampaign field.
func (r *mutationResolver) DeleteCampaign(ctx context.Context, id string) (*model.DeletionResult, error) {
	return campaignRouter.Delete(ctx, id)
}

// CampaignByID is the resolver for the campaignById field.
func (r *queryResolver) CampaignByID(ctx context.Context, id string) (*model.Campaigns, error) {
	return campaignRouter.Get(ctx, id)
}

// GetAllCampaigns is the resolver for the getAllCampaigns field.
func (r *queryResolver) GetAllCampaigns(ctx context.Context, campaignFilter *model.CampaignFilter) ([]*model.Campaigns, error) {
	return campaignRouter.GetAll(ctx, campaignFilter)
}
