package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.43

import (
	"adtec/backend/src/graphql/model"
	"adtec/backend/src/router/channelBalanceRouter"
	"context"
)

// CreateChannelBalance is the resolver for the createChannelBalance field.
func (r *mutationResolver) CreateChannelBalance(ctx context.Context, input model.CreateChannelBalanceInput) (*model.ChannelBalances, error) {
	return channelBalanceRouter.Create(ctx, input)
}

// UpdateChannelBalance is the resolver for the updateChannelBalance field.
func (r *mutationResolver) UpdateChannelBalance(ctx context.Context, input model.UpdateChannelBalanceInput) (*model.ChannelBalances, error) {
	return channelBalanceRouter.Update(ctx, input)
}

// ChannelBalanceByID is the resolver for the channelBalanceById field.
func (r *queryResolver) ChannelBalanceByID(ctx context.Context, channelID string) (*model.ChannelBalances, error) {
	return channelBalanceRouter.Get(ctx, channelID)
}
