package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.43

import (
	"adtec/backend/src/graphql/model"
	"adtec/backend/src/router/channelCategoryRouter"
	"context"
)

// CreateChannelCategory is the resolver for the createChannelCategory field.
func (r *mutationResolver) CreateChannelCategory(ctx context.Context, input model.ChannelCategoryInput) (*model.ChannelCategories, error) {
	return channelCategoryRouter.Create(ctx, input)
}

// DeleteChannelCategory is the resolver for the deleteChannelCategory field.
func (r *mutationResolver) DeleteChannelCategory(ctx context.Context, channelCategoryInput *model.ChannelCategoryInput) (*model.DeletionResult, error) {
	return channelCategoryRouter.Delete(ctx, channelCategoryInput)
}

// GetAllChannelCategories is the resolver for the getAllChannelCategories field.
func (r *queryResolver) GetAllChannelCategories(ctx context.Context, channelCategoryFilter *model.ChannelCategoryFilter) ([]*model.ChannelCategories, error) {
	return channelCategoryRouter.GetAll(ctx, channelCategoryFilter)
}
