package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.43

import (
	"adtec/backend/src/graphql/model"
	"adtec/backend/src/router/channelContentLanguageRouter"
	"context"
)

// CreateChannelContentLanguage is the resolver for the createChannelContentLanguage field.
func (r *mutationResolver) CreateChannelContentLanguage(ctx context.Context, input model.ChannelContentLanguageInput) (*model.ChannelContentLanguages, error) {
	return channelContentLanguageRouter.Create(ctx, input)
}

// DeleteChannelContentLanguage is the resolver for the deleteChannelContentLanguage field.
func (r *mutationResolver) DeleteChannelContentLanguage(ctx context.Context, channelContentLanguageInput *model.ChannelContentLanguageInput) (*model.DeletionResult, error) {
	return channelContentLanguageRouter.Delete(ctx, channelContentLanguageInput)
}

// GetAllChannelContentLanguages is the resolver for the getAllChannelContentLanguages field.
func (r *queryResolver) GetAllChannelContentLanguages(ctx context.Context, channelContentLanguageFilter *model.ChannelContentLanguageFilter) ([]*model.ChannelContentLanguages, error) {
	return channelContentLanguageRouter.GetAll(ctx, channelContentLanguageFilter)
}
