package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.43

import (
	"adtec/backend/src/graphql/model"
	"adtec/backend/src/router/channelLifeTimeBalanceRouter"
	"context"
)

// CreateChannelLifeTimeBalance is the resolver for the createChannelLifeTimeBalance field.
func (r *mutationResolver) CreateChannelLifeTimeBalance(ctx context.Context, input model.CreateChannelLifeTimeBalanceInput) (*model.ChannelLifeTimeBalances, error) {
	return channelLifeTimeBalanceRouter.Create(ctx, input)
}

// UpdateChannelLifeTimeBalance is the resolver for the updateChannelLifeTimeBalance field.
func (r *mutationResolver) UpdateChannelLifeTimeBalance(ctx context.Context, input model.UpdateChannelLifeTimeBalanceInput) (*model.ChannelLifeTimeBalances, error) {
	return channelLifeTimeBalanceRouter.Update(ctx, input)
}

// ChannelLifeTimeBalanceByID is the resolver for the channelLifeTimeBalanceById field.
func (r *queryResolver) ChannelLifeTimeBalanceByID(ctx context.Context, channelID string) (*model.ChannelLifeTimeBalances, error) {
	return channelLifeTimeBalanceRouter.Get(ctx, channelID)
}
