package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.43

import (
	"adtec/backend/src/graphql/model"
	"adtec/backend/src/router/channelDetailRouter"
	"context"
)

// CreateChannelDetail is the resolver for the createChannelDetail field.
func (r *mutationResolver) CreateChannelDetail(ctx context.Context, input model.CreateChannelDetailInput) (*model.ChannelDetails, error) {
	return channelDetailRouter.Create(ctx, input)
}

// UpdateChannelDetail is the resolver for the updateChannelDetail field.
func (r *mutationResolver) UpdateChannelDetail(ctx context.Context, input model.UpdateChannelDetailInput) (*model.ChannelDetails, error) {
	return channelDetailRouter.Update(ctx, input)
}

// GetAllChannelDetails is the resolver for the getAllChannelDetails field.
func (r *queryResolver) GetAllChannelDetails(ctx context.Context, channelDetailFilter *model.ChannelDetailFilter) ([]*model.ChannelDetails, error) {
	return channelDetailRouter.GetAll(ctx, channelDetailFilter)
}

// ChannelDetailByID is the resolver for the channelDetailById field.
func (r *queryResolver) ChannelDetailByID(ctx context.Context, channelID string) (*model.ChannelDetails, error) {
	return channelDetailRouter.Get(ctx, channelID)
}
