package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.43

import (
	"adtec/backend/src/graphql/model"
	"adtec/backend/src/router/companyBankingRouter"
	"context"
)

// CreateCompanyBanking is the resolver for the createCompanyBanking field.
func (r *mutationResolver) CreateCompanyBanking(ctx context.Context, input model.CreateCompanyBankingInput) (*model.CompanyBankings, error) {
	return companyBankingRouter.Create(ctx, input)
}

// DeleteCompanyBanking is the resolver for the deleteCompanyBanking field.
func (r *mutationResolver) DeleteCompanyBanking(ctx context.Context, id string) (*model.DeletionResult, error) {
	return companyBankingRouter.Delete(ctx, id)
}

// CompanyBankingByID is the resolver for the companyBankingById field.
func (r *queryResolver) CompanyBankingByID(ctx context.Context, id string) (*model.CompanyBankings, error) {
	return companyBankingRouter.Get(ctx, id)
}

// GetAllCompanyBankings is the resolver for the getAllCompanyBankings field.
func (r *queryResolver) GetAllCompanyBankings(ctx context.Context, companyBankingsFilter model.CompanyBankingFilter) ([]*model.CompanyBankings, error) {
	return companyBankingRouter.GetAll(ctx, companyBankingsFilter)
}
