package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.43

import (
	"adtec/backend/src/graphql/model"
	"adtec/backend/src/router/companyRouter"
	"context"
)

// CreateCompany is the resolver for the createCompany field.
func (r *mutationResolver) CreateCompany(ctx context.Context, input model.CreateCompanyInput) (*model.Companies, error) {
	return companyRouter.Create(ctx, input)
}

// UpdateCompany is the resolver for the updateCompany field.
func (r *mutationResolver) UpdateCompany(ctx context.Context, input model.UpdateCompanyInput) (*model.Companies, error) {
	return companyRouter.Update(ctx, input)
}

// CompanyByID is the resolver for the companyById field.
func (r *queryResolver) CompanyByID(ctx context.Context, id string) (*model.Companies, error) {
	return companyRouter.Get(ctx, id)
}
