package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.43

import (
	"adtec/backend/src/graphql/model"
	"adtec/backend/src/router/companyMemberRouter"
	"context"
)

// CreateCompanyMember is the resolver for the createCompanyMember field.
func (r *mutationResolver) CreateCompanyMember(ctx context.Context, input model.CreateCompanyMemberInput) (*model.CompanyMembers, error) {
	return companyMemberRouter.Create(ctx, input)
}

// UpdateCompanyMember is the resolver for the updateCompanyMember field.
func (r *mutationResolver) UpdateCompanyMember(ctx context.Context, input model.UpdateCompanyMemberInput) (*model.CompanyMembers, error) {
	return companyMemberRouter.Update(ctx, input)
}

// CompanyMemberByID is the resolver for the companyMemberById field.
func (r *queryResolver) CompanyMemberByID(ctx context.Context, id string) (*model.CompanyMembers, error) {
	return companyMemberRouter.Get(ctx, id)
}

// GetAllCompanyMembers is the resolver for the getAllCompanyMembers field.
func (r *queryResolver) GetAllCompanyMembers(ctx context.Context, companyMemberFilter *model.CompanyMemberFilter) ([]*model.CompanyMembers, error) {
	return companyMemberRouter.GetAll(ctx, companyMemberFilter)
}
