package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.43

import (
	"adtec/backend/src/graphql/model"
	"adtec/backend/src/router/contentLinkRouter"
	"context"
)

// CreateContentLink is the resolver for the createContentLink field.
func (r *mutationResolver) CreateContentLink(ctx context.Context, input model.CreateContentLinkInput) (*model.ContentLinks, error) {
	return contentLinkRouter.Create(ctx, input)
}

// UpdateContentLink is the resolver for the updateContentLink field.
func (r *mutationResolver) UpdateContentLink(ctx context.Context, input model.UpdateContentLinkInput) (*model.ContentLinks, error) {
	return contentLinkRouter.Update(ctx, input)
}

// ContentLinkByID is the resolver for the contentLinkById field.
func (r *queryResolver) ContentLinkByID(ctx context.Context, id string) (*model.ContentLinks, error) {
	return contentLinkRouter.Get(ctx, id)
}
