package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.43

import (
	"adtec/backend/src/graphql/model"
	"adtec/backend/src/router/contentRouter"
	"context"
)

// CreateContent is the resolver for the createContent field.
func (r *mutationResolver) CreateContent(ctx context.Context, input model.CreateContentInput) (*model.Contents, error) {
	return contentRouter.Create(ctx, input)
}

// UpdateContent is the resolver for the updateContent field.
func (r *mutationResolver) UpdateContent(ctx context.Context, input model.UpdateContentInput) (*model.Contents, error) {
	return contentRouter.Update(ctx, input)
}

// ContentByID is the resolver for the contentById field.
func (r *queryResolver) ContentByID(ctx context.Context, id string) (*model.Contents, error) {
	return contentRouter.Get(ctx, id)
}
