package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.43

import (
	"adtec/backend/src/graphql/model"
	"adtec/backend/src/router/CPMRateRouter"
	"context"
)

// CreateCPMRate is the resolver for the createCPMRate field.
func (r *mutationResolver) CreateCPMRate(ctx context.Context, input model.CreateCPMRateInput) (*model.CpmRates, error) {
	return CPMRateRouter.Create(ctx, input)
}

// UpdateCPMRate is the resolver for the updateCPMRate field.
func (r *mutationResolver) UpdateCPMRate(ctx context.Context, input model.UpdateCPMRateInput) (*model.CpmRates, error) {
	return CPMRateRouter.Update(ctx, input)
}

// CpmRateByChannelID is the resolver for the cpmRateByChannelId field.
func (r *queryResolver) CpmRateByChannelID(ctx context.Context, channelID string) (*model.CpmRates, error) {
	return CPMRateRouter.Get(ctx, channelID)
}
