package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.43

import (
	"adtec/backend/src/graphql/model"
	"adtec/backend/src/router/languageRouter"
	"context"
	"fmt"
)

// CreateLanguage is the resolver for the createLanguage field.
func (r *mutationResolver) CreateLanguage(ctx context.Context, input model.CreateLanguageInput) (*model.Languages, error) {
	return languageRouter.Create(ctx, input)
}

// LanguageByID is the resolver for the languageById field.
func (r *queryResolver) LanguageByID(ctx context.Context, id string) (*model.Languages, error) {
	return languageRouter.Get(ctx, id)
}

// GetAllLanguages is the resolver for the getAllLanguages field.
func (r *queryResolver) GetAllLanguages(ctx context.Context, languageFilter *model.LanguageFilter) ([]*model.Languages, error) {
	panic(fmt.Errorf("not implemented: GetAllLanguages - getAllLanguages"))
}

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//   - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//     it when you're done.
//   - You have helper methods in this file. Move them out to keep these resolver files clean.
func (r *queryResolver) Languages(ctx context.Context, languageFilter *model.LanguageFilter) ([]*model.Languages, error) {
	return languageRouter.GetAll(ctx, languageFilter)
}
