package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.43

import (
	"adtec/backend/src/graphql/model"
	"adtec/backend/src/router/withdrawalChannelLinkRouter"
	"context"
)

// CreateWithdrawalChannelLink is the resolver for the createWithdrawalChannelLink field.
func (r *mutationResolver) CreateWithdrawalChannelLink(ctx context.Context, input model.WithdrawalChannelLinkInput) (*model.WithdrawalChannelLinks, error) {
	return withdrawalChannelLinkRouter.Create(ctx, input)
}

// DeleteWithdrawalChannelLink is the resolver for the deleteWithdrawalChannelLink field.
func (r *mutationResolver) DeleteWithdrawalChannelLink(ctx context.Context, withdrawalChannelLinkInput *model.WithdrawalChannelLinkInput) (*model.DeletionResult, error) {
	return withdrawalChannelLinkRouter.Delete(ctx, withdrawalChannelLinkInput)
}

// WithdrawalChannelLinkByID is the resolver for the withdrawalChannelLinkById field.
func (r *queryResolver) WithdrawalChannelLinkByID(ctx context.Context, withdrawalID string) (*model.WithdrawalChannelLinks, error) {
	return withdrawalChannelLinkRouter.Get(ctx, withdrawalID)
}

// WithdrawalChannelLink is the resolver for the withdrawalChannelLink field.
func (r *queryResolver) WithdrawalChannelLink(ctx context.Context, withdrawalChannelLinkInput *model.WithdrawalChannelLinkInput) (*model.WithdrawalChannelLinks, error) {
	return withdrawalChannelLinkRouter.GetByChannelIdAndAdPaymentId(ctx, withdrawalChannelLinkInput)
}

// GetAllWithdrawalChannelLinks is the resolver for the getAllWithdrawalChannelLinks field.
func (r *queryResolver) GetAllWithdrawalChannelLinks(ctx context.Context, withdrawalChannelLinkFilter *model.WithdrawalChannelLinkFilter) ([]*model.WithdrawalChannelLinks, error) {
	return withdrawalChannelLinkRouter.GetAll(ctx, withdrawalChannelLinkFilter)
}
